### ISSUE TITLE
Frontend - CORS Policy Error

### ISSUE THREAD

**Issue by julio1927** [hyunbin7303/KJ_Ecommerce#13]
CORS Policy Error when fetching data from local api

**Cause of error: _The response to the CORS request is missing the required Access-Control-Allow-Origin header_**
_**Cross-Origin Resource Sharing (CORS) is an HTTP-header based mechanism that allows a server to indicate any other origins (domain, scheme, or port) than its own from which a browser should permit loading of resources**_

**Temporary Fix for use of 1 api call is to use proxy "proxy": "http://localhost:54501" in package.json**

https://www.youtube.com/watch?v=hxyp_LkKDdk&ab_channel=HongLy

**Comment by hyunbin7303** [comment]
@julio1927 What is the root cause of this issue?
