### ISSUE TITLE
Backend - AutoMapper setting up.

### ISSUE THREAD

**Issue by hyunbin7303** [hyunbin7303/KJ_Ecommerce#38]
- [x] AutoMapper Nuget Installation
- [x] AutoMapper Config
- [x] Implement AutoMapper

**Comment by hyunbin7303** [comment]
@julio1927 I guess setting up potion is done; I will create a new ticket to integrate service layer and automapper.

**Comment by julio1927** [comment]
> @julio1927 I guess setting up potion is done; I will create a new ticket to integrate service layer and automapper.

okay sounds good !
